### PR TITLE
Support `auth_user` and `auth_query` options

### PR DESCRIPTION
**Pull request by pks-t**
**Description of the change**

PgBouncer allows querying Postgres directly for login credentials
instead of setting up a PgBouncer-specific user. This is done by
specifying an `auth_query`, which asks the database for credentials of a
given user. The user used by PgBouncer to run this query can be
configured via `auth_user`. Both of these options aren't supported by
images currently.

Support both via two new environment variables `PGBOUNCER_AUTH_QUERY`
and `PGBOUNCER_AUTH_USER`.

**Benefits**

Above two variables can be controlled in PgBouncer.

**Possible drawbacks**

None that I'd know of.

**Applicable issues**

None.

### CODE REVIEW

**Review by javsalgar — APPROVED** [review]
LGTM! Thanks

**Comment by kakoni** [comment]
Hi @javsalgar!  I believe this change got overwritten in https://github.com/bitnami/bitnami-docker-pgbouncer/commit/1cc34c91be167b08d10ff889c6baba0b26fd6dc5

**Comment by javsalgar** [comment]
I see. I forced a new release with the change, it seems that it got lost.

**Comment by kakoni** [comment]
Thank you!

**Pull request merged**
